import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { buildSchema, parse, validate } from "graphql";
import { ENTITIES, buildCountQuery, buildQuery } from "../src/core/backup.js";
import { buildBatchMutation, buildResolveQuery } from "../src/core/batch.js";

/**
 * Offline contract test: every GraphQL document embedded in src/ must validate
 * against the vendored Linear schema (test/fixtures/linear-schema.graphql).
 * Catches variable-type mismatches such as `$id: String!` feeding a filter
 * comparator that expects `ID`, which Linear otherwise rejects only at runtime:
 *   Variable "$id" of type "String!" used in position expecting type "ID".
 */

const SRC = join(import.meta.dir, "..", "src");
const SCHEMA = buildSchema(
  readFileSync(join(import.meta.dir, "fixtures", "linear-schema.graphql"), "utf8"),
);

/** Real count at time of writing is higher; this floor stops a broken
 *  extractor from passing vacuously. Raise it when documents are added. */
const MIN_DOCUMENTS = 60;

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (p.endsWith(".ts") || p.endsWith(".tsx")) out.push(p);
  }
  return out;
}

interface Doc {
  file: string;
  text: string;
  interpolated: boolean;
}

/** Template literals whose body starts with query/mutation/subscription
 *  (optionally after a `/* GraphQL *\/` tag). `${...}` is replaced with a
 *  neutral token so dynamically assembled documents still parse. */
function extractDocuments(): Doc[] {
  const docs: Doc[] = [];
  const re = /`([^`]*)`/g;
  for (const file of walk(SRC)) {
    const src = readFileSync(file, "utf8");
    for (const m of src.matchAll(re)) {
      const body = m[1];
      const lineStart = src.lastIndexOf("\n", m.index) + 1;
      if (/^\s*(\*|\/\/)/.test(src.slice(lineStart, m.index))) continue; // inside a comment
      const interpolated = body.includes("${");
      // A document: operation keyword, optional name, optional variable list,
      // then a selection set. Error-message strings that merely start with
      // the word "mutation" do not match. The runtime-assembled documents in
      // batch.ts declare their variables via interpolation.
      const isDoc = interpolated
        ? /^\s*(query|mutation)\s+\w+\(\$\{/.test(body)
        : /^\s*(query|mutation|subscription)\s*\w*\s*(\([^)]*\))?\s*\{/.test(body);
      if (!isDoc) continue;
      docs.push({ file: file.slice(SRC.length + 1), text: body, interpolated });
    }
  }
  return docs;
}

/** Documents built at runtime, generated by calling the real builders. */
function generated(): Array<{ label: string; text: string }> {
  const out: Array<{ label: string; text: string }> = [];
  for (const spec of ENTITIES) {
    out.push({ label: `backup ${spec.name}`, text: buildQuery(spec) });
    if (spec.kind !== "connection") continue;
    if (spec.sinceFilter) out.push({ label: `backup ${spec.name} (since)`, text: buildQuery(spec, `{ updatedAt: { gte: "2026-01-01T00:00:00.000Z" } }`) });
    if (spec.teamFilter) out.push({ label: `backup ${spec.name} (team)`, text: buildQuery(spec, spec.teamFilter(`"AA", "BB"`)) });
    out.push({ label: `count ${spec.name}`, text: buildCountQuery(spec) });
  }
  for (const n of [1, 3]) {
    out.push({ label: `batch resolve x${n}`, text: buildResolveQuery(n) });
    out.push({ label: `batch mutation x${n}`, text: buildBatchMutation(n) });
  }
  return out;
}

function opName(text: string): string {
  const def = parse(text).definitions[0];
  return def.kind === "OperationDefinition" ? def.name?.value ?? "" : "";
}

/** Independent of the extractor: scan raw source (comment lines dropped) for
 *  `query|mutation <Name>` followed by `(`, `{` or `$` (interpolation). */
/** `query ${name} {` / `mutation ${name}(`: a fully interpolated operation
 *  name has no static stem, so the stem scan below cannot see it. Prose such as
 *  `mutation ${count} rows` has no following `(`/`{` and stays unmatched. */
const INTERPOLATED_NAME_RE = /\b(?:query|mutation|subscription)\s+\$\{[^}]*\}\s*[({]/g;

function sourceWithoutComments(file: string): string {
  return readFileSync(file, "utf8")
    .split("\n")
    .filter((l) => !/^\s*(\*|\/\/|\/\*)/.test(l))
    .join("\n");
}

function scannedOperationStems(): string[] {
  const stems: string[] = [];
  for (const file of walk(SRC)) {
    const text = sourceWithoutComments(file);
    for (const m of text.matchAll(/\b(?:query|mutation|subscription)\s*([A-Za-z_][\w]*)?\s*(?:[({]|(?<=\w)\$\{)/g)) {
      // `query {` inside prose or code such as "mutation ${count}" has no name token
      stems.push(m[1] ?? "");
    }
  }
  return stems;
}

describe("embedded GraphQL documents validate against the Linear schema", () => {
  const docs = extractDocuments().filter((d) => !d.interpolated);
  const gen = generated();

  test(`extractor found at least ${MIN_DOCUMENTS} static documents`, () => {
    console.log(`graphql-documents: ${docs.length} static + ${gen.length} generated`);
    expect(docs.length).toBeGreaterThanOrEqual(MIN_DOCUMENTS);
    expect(gen.length).toBeGreaterThanOrEqual(ENTITIES.length);
  });

  for (const d of docs) {
    test(`${d.file}: ${d.text.trim().split("\n")[0].slice(0, 70)}`, () => {
      expect(validate(SCHEMA, parse(d.text)).map((e) => e.message)).toEqual([]);
    });
  }
  for (const g of gen) {
    test(`generated: ${g.label}`, () => {
      expect(validate(SCHEMA, parse(g.text)).map((e) => e.message)).toEqual([]);
    });
  }

  test("every operation template in src/ is validated (independent scan)", () => {
    const validated = [...docs.map((d) => opName(d.text)), ...gen.map((g) => opName(g.text))];
    const stems = scannedOperationStems();
    expect(stems.length).toBeGreaterThanOrEqual(MIN_DOCUMENTS);
    const uncovered = stems.filter(
      (s) => !validated.some((v) => v === s || (s.endsWith("_") && v.startsWith(s))),
    );
    expect([...new Set(uncovered)]).toEqual([]);
  });
});

describe("fully interpolated operation names", () => {
  test("the pattern matches an interpolated name and not prose (control)", () => {
    expect("const q = `query ${name} { viewer { id } }`".match(INTERPOLATED_NAME_RE)).not.toBeNull();
    expect("`mutation ${op}($id: ID!) { x }`".match(INTERPOLATED_NAME_RE)).not.toBeNull();
    expect("`${count} rows: mutation ${count} applied`".match(INTERPOLATED_NAME_RE)).toBeNull();
  });

  test("no source document interpolates its whole operation name", () => {
    const hits: string[] = [];
    for (const file of walk(SRC))
      for (const m of sourceWithoutComments(file).matchAll(INTERPOLATED_NAME_RE)) hits.push(`${file}: ${m[0]}`);
    // Name the operation statically so the schema validation above covers it.
    expect(hits).toEqual([]);
  });
});
