apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.loopRecipes.configMapName }}
  labels:
    app.kubernetes.io/name: linearctl
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $path, $_ := .Files.Glob "../.linearctl/loop-recipes/*.md" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
